spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jankominek.highwaycontracts.dto
        spring.json.value.default.type: com.jankominek.highwaycontracts.dto.HighwayAlert
        spring.json.use.type.headers: false

app:
  notification:
    topics:
      speeding-alerts: speeding-alerts
      stolen-vehicles: stolen-vehicles
      traffic-jam-alerts: traffic-jam-alerts
      highway-alerts: highway-alerts

server:
  port: 8083
