spring:
  application:
    name: highway-processor

  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: highway-processor
      properties:
        processing.guarantee: exactly_once_v2
        replication.factor: 1

server:
  port: 8082

app:
  highway:
    input-topic: camera-simulator
    speeding-alerts-topic: speeding-alerts
    alerts-topic: highway-alerts
    stolen-vehicles-topic: stolen-vehicles
    traffic-jam-alerts-topic: traffic-jam-alerts

    speeding:
      speed-limit-kmh: 120
      max-interval: 30s
      distances-km:
        GANTRYAB: 0.5
        GANTRYBC: 0.5

    traffic-jam:
      window: 1m
      grace-period: 10s
      threshold: 15